import assert from 'node:assert/strict'
import { runSeraVNextEngineV0 } from '../../frontend/src/lib/sera-vnext/engine-v0/run-engine'
import type { SeraSemanticEvidenceAnnotation } from '../../frontend/src/lib/sera-vnext/engine-contract'

function run(inputId: string, narrative: string, semanticEvidence: SeraSemanticEvidenceAnnotation[]) {
  return runSeraVNextEngineV0({
    inputId,
    narrative,
    locale: 'pt-BR',
    sourceType: 'real_event',
    requestId: inputId,
    mode: 'CANDIDATE_ONLY',
    semanticEvidence,
    semanticEnrichmentMeta: {
      provider: 'frozen-calibration-semantics',
      model: 'semantic-contract-v2',
      requestedAt: 'frozen',
      acceptedAnnotations: semanticEvidence.length,
      rejectedAnnotations: 0,
      schemaVersion: 'SERA_SEMANTIC_AI_V2',
    },
    options: { allowLlm: true, requireHumanReview: true, includeDebugTrace: true },
  })
}

function a(args: Omit<SeraSemanticEvidenceAnnotation, 'id'> & { id: string }): SeraSemanticEvidenceAnnotation { return args }

const cal06Narrative = 'Durante o pouso em uma unidade marítima, o copiloto informou ao comandante que a área lateral estava livre. A frase foi baseada em uma mensagem recebida parcialmente pelo intercom; a equipe de convés havia dito que a área estaria livre “após a retirada do equipamento”, mas a parte final da transmissão não foi ouvida com clareza. O copiloto não confirmou a mensagem e repassou a informação como se fosse definitiva. O comandante iniciou a continuação da manobra e interrompeu ao visualizar o equipamento ainda na área. A investigação não identificou defeito visual, desconhecimento do procedimento ou intenção de violar limites. Havia ainda um padrão de comunicação muito conciso na tripulação e pouca contestação entre os dois pilotos.'
const cal06 = run('CAL-06-REGRESSION-V2', cal06Narrative, [
  a({ id: 'C06-FIRST', sourceQuote: 'O copiloto não confirmou a mensagem', sourceSentenceIndex: 2, roles: ['FIRST_DEPARTURE', 'DIRECT_ACTOR'], concepts: [], actor: 'copiloto', temporalRelation: 'AT_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: null, actionFailureMechanism: 'OTHER_ACTION_FAILURE', actionMechanismEvidenceQuote: 'O copiloto não confirmou a mensagem', displayInterpretation: null, confidence: 'HIGH', rationale: 'Primeira saída.' }),
  a({ id: 'C06-P', sourceQuote: 'repassou a informação como se fosse definitiva', sourceSentenceIndex: 2, roles: ['PERCEPTION_STATE'], concepts: ['inadequateAssessment'], actor: 'copiloto', temporalRelation: 'AT_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: null, actionFailureMechanism: 'NONE_OR_UNKNOWN', actionMechanismEvidenceQuote: null, displayInterpretation: 'O operador percebia a informação recebida como definitiva.', confidence: 'HIGH', rationale: 'Tratou informação parcial como definitiva no ponto de fuga.' }),
  a({ id: 'C06-INFO', sourceQuote: 'a parte final da transmissão não foi ouvida com clareza', sourceSentenceIndex: 1, roles: ['PRECONDITION'], concepts: ['informationUnavailable'], actor: 'copiloto', temporalRelation: 'PRE_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: 'PRESENT_CONTEXT', actionFailureMechanism: 'NONE_OR_UNKNOWN', actionMechanismEvidenceQuote: null, displayInterpretation: null, confidence: 'HIGH', rationale: 'Parte crítica da transmissão não chegou com clareza ao ator.' }),
  a({ id: 'C06-LATER', sourceQuote: 'iniciou a continuação da manobra', sourceSentenceIndex: 3, roles: ['CRITICAL_UNSAFE_ACT', 'DIRECT_ACTOR'], concepts: ['implementedAction'], actor: 'comandante', temporalRelation: 'POST_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: null, actionFailureMechanism: 'NONE_OR_UNKNOWN', actionMechanismEvidenceQuote: null, displayInterpretation: null, confidence: 'HIGH', rationale: 'Ato posterior do comandante.' }),
  a({ id: 'C06-SOCIAL', sourceQuote: 'Havia ainda um padrão de comunicação muito conciso na tripulação e pouca contestação entre os dois pilotos.', sourceSentenceIndex: 5, roles: ['PRECONDITION'], concepts: [], actor: null, temporalRelation: 'PRE_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: 'SOCIAL', preconditionCausalStatus: 'PRESENT_CONTEXT', actionFailureMechanism: 'NONE_OR_UNKNOWN', actionMechanismEvidenceQuote: null, displayInterpretation: null, confidence: 'HIGH', rationale: 'Dinâmica de equipe presente sem nexo causal automático.' }),
])
assert.equal(cal06.directActor.actor, 'copiloto')
assert.equal(cal06.axes.perception.proposedCode, 'P-H', 'missing/degraded communication content should reach P-H through the canonical P tree')
assert.equal(cal06.axes.objective.proposedCode, null)
assert.equal(cal06.escapePoint.criticalUnsafeActActor, 'comandante')
assert.equal(cal06.axes.perception.supportingEvidence.some((text) => /continua[cç][aã]o da manobra/i.test(text)), false, 'later commander action must not contaminate copilot P')
assert.ok(cal06.preconditions.some((item) => item.canonicalCategory === 'SOCIAL' && !item.basedOnCandidateCode))

const cal07Narrative = 'Após uma sequência de atrasos por meteorologia, a tripulação iniciou a preparação para uma etapa final com o objetivo explícito de evitar o cancelamento e recuperar o horário da programação. A aeronave e o aeródromo estavam operacionais e não há evidência de que a tripulação tenha conscientemente ultrapassado um limite regulamentar ou uma proibição formal. Entretanto, o comandante decidiu abreviar uma pausa prevista no fluxo normal de preparação e prosseguir com a operação para ganhar tempo, aumentando a carga de tarefas simultâneas. Durante essa sequência, uma configuração precisou ser revista antes da decolagem. Nas entrevistas, ambos afirmaram que a preocupação dominante naquele momento era “não perder mais tempo” e concluir a programação.'
const cal07 = run('CAL-07-REGRESSION-V2', cal07Narrative, [
  a({ id: 'C07-FIRST', sourceQuote: 'decidiu abreviar uma pausa prevista no fluxo normal de preparação', sourceSentenceIndex: 2, roles: ['FIRST_DEPARTURE', 'CRITICAL_UNSAFE_ACT', 'DIRECT_ACTOR'], concepts: [], actor: 'comandante', temporalRelation: 'AT_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: null, actionFailureMechanism: 'OTHER_ACTION_FAILURE', actionMechanismEvidenceQuote: 'decidiu abreviar uma pausa prevista no fluxo normal de preparação', displayInterpretation: null, confidence: 'HIGH', rationale: 'Primeira saída.' }),
  a({ id: 'C07-O', sourceQuote: 'prosseguir com a operação para ganhar tempo', sourceSentenceIndex: 2, roles: ['OBJECTIVE_INTENT'], concepts: ['efficiencyObjective', 'unmanagedRisk'], actor: 'comandante', temporalRelation: 'AT_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: null, actionFailureMechanism: 'NONE_OR_UNKNOWN', actionMechanismEvidenceQuote: null, displayInterpretation: 'O operador pretendia ganhar tempo e recuperar a programação.', confidence: 'HIGH', rationale: 'A finalidade temporal está ligada à decisão do comandante no primeiro desvio.' }),
  a({ id: 'C07-TIME', sourceQuote: 'a preocupação dominante naquele momento era “não perder mais tempo” e concluir a programação', sourceSentenceIndex: 4, roles: ['PRECONDITION'], concepts: ['timeManagementPressure'], actor: 'comandante', temporalRelation: 'AT_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: 'TIME_PRESSURE', preconditionCausalStatus: 'PRESENT_CONTEXT', actionFailureMechanism: 'NONE_OR_UNKNOWN', actionMechanismEvidenceQuote: null, displayInterpretation: null, confidence: 'HIGH', rationale: 'Pressão temporal explícita.' }),
  a({ id: 'C07-LOAD', sourceQuote: 'aumentando a carga de tarefas simultâneas', sourceSentenceIndex: 2, roles: ['PRECONDITION'], concepts: ['attentionPressure'], actor: 'comandante', temporalRelation: 'AT_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: 'PRESENT_CONTEXT', actionFailureMechanism: 'NONE_OR_UNKNOWN', actionMechanismEvidenceQuote: null, displayInterpretation: null, confidence: 'HIGH', rationale: 'Carga concorrente contemporânea.' }),
])
assert.equal(cal07.directActor.actor, 'comandante')
assert.equal(cal07.axes.perception.proposedCode, null)
assert.equal(cal07.axes.objective.proposedCode, 'O-D', 'explicit time/schedule goal pursued through task compression should reach the canonical non-violation intention branch')
assert.ok(cal07.axes.objective.supportingEvidence.some((text) => /ganhar tempo/i.test(text)))
assert.ok(cal07.preconditions.some((item) => item.canonicalCategory === 'TIME_PRESSURE' && !item.basedOnCandidateCode))

const cal08Narrative = 'Uma sequência de voos foi programada com tempos de solo mínimos e sem margem para reabastecimento não previsto. A área de planejamento já possuía registros de que a combinação de rota, número de passageiros e disponibilidade de apoio frequentemente exigia mais tempo do que o planejado. Mesmo assim, a programação foi mantida por várias semanas. No dia do evento, um atraso inicial tornou o restante da sequência impraticável sem compressão de tarefas. A supervisão recebeu a informação, mas orientou a equipe a “tentar recuperar” sem replanejar os setores. Em uma das pernas, a tripulação omitiu uma verificação e precisou interromper a operação para corrigi-la. Não houve defeito técnico. A investigação aponta condições individuais, de equipe e de tarefa, mas também decisões de planejamento e supervisão anteriores ao voo.'
const cal08 = run('CAL-08-REGRESSION-V2', cal08Narrative, [
  a({ id: 'C08-FIRST', sourceQuote: 'a tripulação omitiu uma verificação', sourceSentenceIndex: 5, roles: ['FIRST_DEPARTURE'], concepts: ['proceduralOmission'], actor: null, temporalRelation: 'AT_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: null, actionFailureMechanism: 'PROCEDURAL_OMISSION', actionMechanismEvidenceQuote: 'a tripulação omitiu uma verificação', displayInterpretation: null, confidence: 'HIGH', rationale: 'Ator não individualizado.' }),
  a({ id: 'C08-SUP', sourceQuote: 'A supervisão recebeu a informação, mas orientou a equipe a “tentar recuperar” sem replanejar os setores.', sourceSentenceIndex: 4, roles: ['PRECONDITION'], concepts: [], actor: null, temporalRelation: 'PRE_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: 'MONITORING_SUPERVISION', preconditionCausalStatus: 'PRESENT_CONTEXT', actionFailureMechanism: 'NONE_OR_UNKNOWN', actionMechanismEvidenceQuote: null, displayInterpretation: null, confidence: 'HIGH', rationale: 'Supervisão contextual.' }),
  a({ id: 'C08-TIME', sourceQuote: 'um atraso inicial tornou o restante da sequência impraticável sem compressão de tarefas', sourceSentenceIndex: 3, roles: ['PRECONDITION'], concepts: ['timeManagementPressure'], actor: null, temporalRelation: 'PRE_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: 'TIME_PRESSURE', preconditionCausalStatus: 'PRESENT_CONTEXT', actionFailureMechanism: 'NONE_OR_UNKNOWN', actionMechanismEvidenceQuote: null, displayInterpretation: null, confidence: 'HIGH', rationale: 'Pressão temporal efetiva.' }),
  a({ id: 'C08-ORG', sourceQuote: 'Mesmo assim, a programação foi mantida por várias semanas.', sourceSentenceIndex: 2, roles: ['PRECONDITION'], concepts: [], actor: null, temporalRelation: 'PRE_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: 'ORGANIZATIONAL_PROCESS_PRACTICES', preconditionCausalStatus: 'PRESENT_CONTEXT', actionFailureMechanism: 'NONE_OR_UNKNOWN', actionMechanismEvidenceQuote: null, displayInterpretation: null, confidence: 'HIGH', rationale: 'Planejamento organizacional persistente.' }),
  a({ id: 'C08-OVER', sourceQuote: 'A área de planejamento já possuía registros de que a combinação de rota, número de passageiros e disponibilidade de apoio frequentemente exigia mais tempo do que o planejado.', sourceSentenceIndex: 1, roles: ['PRECONDITION'], concepts: [], actor: null, temporalRelation: 'PRE_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: 'OVERSIGHT', preconditionCausalStatus: 'PRESENT_CONTEXT', actionFailureMechanism: 'NONE_OR_UNKNOWN', actionMechanismEvidenceQuote: null, displayInterpretation: null, confidence: 'HIGH', rationale: 'Problema conhecido persistente.' }),
])
assert.equal(cal08.directActor.status, 'AMBIGUOUS')
assert.equal(cal08.canonicalTraversal.paths.length, 0)
for (const canonical of ['MONITORING_SUPERVISION', 'TIME_PRESSURE', 'ORGANIZATIONAL_PROCESS_PRACTICES', 'OVERSIGHT'] as const) {
  assert.ok(cal08.preconditions.some((item) => item.canonicalCategory === canonical && !item.basedOnCandidateCode), `${canonical} must remain visible`)
}

const cal09Narrative = 'Em aproximação noturna para uma instalação marítima, sem horizonte natural visível, o piloto relatou perceber a aeronave mais alta e mais afastada do que realmente estava. As indicações de instrumentos estavam disponíveis e funcionais, mas as luzes da instalação e o fundo escuro produziram uma referência visual enganosa. O piloto corrigiu a trajetória quando o outro tripulante chamou a discrepância entre a impressão visual e os instrumentos. Não há indicação de deficiência visual do piloto, desconhecimento dos instrumentos ou falha de transmissão de informações. O próprio piloto descreveu que sua percepção visual do posicionamento parecia convincente até que comparou novamente com as referências instrumentais.'
const cal09 = run('CAL-09-REGRESSION-V2', cal09Narrative, [
  a({ id: 'C09-FIRST', sourceQuote: 'perceber a aeronave mais alta e mais afastada do que realmente estava', sourceSentenceIndex: 0, roles: ['FIRST_DEPARTURE', 'DIRECT_ACTOR', 'PERCEPTION_STATE'], concepts: ['inadequateAssessment', 'perceptionCapabilityPresent', 'informationAmbiguous'], actor: 'piloto', temporalRelation: 'AT_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: null, actionFailureMechanism: 'NONE_OR_UNKNOWN', actionMechanismEvidenceQuote: null, displayInterpretation: 'O operador percebia a aeronave como mais alta e afastada do que realmente estava.', confidence: 'HIGH', rationale: 'Percepção visual enganosa.' }),
  a({ id: 'C09-ENV', sourceQuote: 'as luzes da instalação e o fundo escuro produziram uma referência visual enganosa', sourceSentenceIndex: 1, roles: ['PRECONDITION'], concepts: [], actor: null, temporalRelation: 'PRE_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: 'ENVIRONMENT', preconditionCausalStatus: 'PRESENT_CONTEXT', actionFailureMechanism: 'NONE_OR_UNKNOWN', actionMechanismEvidenceQuote: null, displayInterpretation: null, confidence: 'HIGH', rationale: 'Contexto ambiental.' }),
])
assert.equal(cal09.axes.perception.proposedCode, 'P-F')
assert.equal(cal09.axes.objective.proposedCode, null)
assert.equal(cal09.axes.action.proposedCode, null)

const cal10Narrative = 'Durante o voo, surgiu uma indicação de sistema conhecida e corretamente percebida pela tripulação. O comandante identificou o alerta e descreveu corretamente o estado da aeronave, mas escolheu uma resposta operacional inadequada porque não conhecia um detalhe específico do procedimento aplicável àquela configuração. Na entrevista, afirmou que nunca havia recebido treinamento prático sobre aquela combinação de condições e que acreditava, de forma sincera, que a ação executada era a prevista. As alternativas estavam disponíveis, não havia pressão temporal dominante e não ocorreu falha sensorial ou de comunicação. Um instrutor demonstrou posteriormente que o procedimento correto constava da documentação técnica e diferia da ação tomada.'
const cal10 = run('CAL-10-REGRESSION-V2', cal10Narrative, [
  a({ id: 'C10-FIRST', sourceQuote: 'escolheu uma resposta operacional inadequada', sourceSentenceIndex: 1, roles: ['FIRST_DEPARTURE', 'CRITICAL_UNSAFE_ACT', 'DIRECT_ACTOR', 'ACTION_STRATEGY'], concepts: ['implementedAction', 'incorrectAction', 'selectionSubtype'], actor: 'comandante', temporalRelation: 'AT_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: null, actionFailureMechanism: 'OTHER_ACTION_FAILURE', actionMechanismEvidenceQuote: 'escolheu uma resposta operacional inadequada porque não conhecia um detalhe específico do procedimento aplicável àquela configuração.', displayInterpretation: 'O operador tentava responder ao alerta por meio da resposta operacional escolhida.', confidence: 'HIGH', rationale: 'Resposta selecionada e implementada.' }),
  a({ id: 'C10-P', sourceQuote: 'identificou o alerta e descreveu corretamente o estado da aeronave', sourceSentenceIndex: 1, roles: ['PERCEPTION_STATE'], concepts: ['adequateAssessment', 'perceptionCapabilityPresent'], actor: 'comandante', temporalRelation: 'AT_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: null, actionFailureMechanism: 'NONE_OR_UNKNOWN', actionMechanismEvidenceQuote: null, displayInterpretation: 'O operador percebia corretamente o alerta e o estado da aeronave.', confidence: 'HIGH', rationale: 'Percepção adequada.' }),
  a({ id: 'C10-KNOW', sourceQuote: 'não conhecia um detalhe específico do procedimento aplicável àquela configuração', sourceSentenceIndex: 1, roles: ['PRECONDITION'], concepts: ['actionKnowledgeLimitation'], actor: 'comandante', temporalRelation: 'AT_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: 'TRAINING_SELECTION', preconditionCausalStatus: 'SOURCE_LINKED', preconditionCausalTargetQuote: 'escolheu uma resposta operacional inadequada', actionFailureMechanism: 'NONE_OR_UNKNOWN', actionMechanismEvidenceQuote: null, displayInterpretation: null, confidence: 'HIGH', rationale: 'Falta de conhecimento procedimental explicitamente ligada à seleção inadequada.' }),
  a({ id: 'C10-TRAIN', sourceQuote: 'nunca havia recebido treinamento prático sobre aquela combinação de condições', sourceSentenceIndex: 2, roles: ['PRECONDITION'], concepts: [], actor: 'comandante', temporalRelation: 'PRE_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: 'TRAINING_SELECTION', preconditionCausalStatus: 'PRESENT_CONTEXT', actionFailureMechanism: 'NONE_OR_UNKNOWN', actionMechanismEvidenceQuote: null, displayInterpretation: null, confidence: 'HIGH', rationale: 'Lacuna de treinamento específico.' }),
])
assert.equal(cal10.axes.perception.proposedCode, 'P-A')
assert.equal(cal10.axes.objective.proposedCode, null)
assert.equal(cal10.axes.action.proposedCode, 'A-E', 'explicit procedural knowledge deficit must stop A at the knowledge/decision leaf before selection subtype')
assert.notEqual(cal10.axes.action.proposedCode, 'A-F')
assert.ok(cal10.preconditions.some((item) => item.canonicalCategory === 'TRAINING_SELECTION' && !item.basedOnCandidateCode), 'training gap must be categorized as TRAINING_SELECTION')
assert.equal(cal10.preconditions.some((item) => !item.basedOnCandidateCode && item.canonicalCategory === 'ORGANIZATIONAL_PROCESS_PRACTICES'), false, 'task-specific training gap must not be relabeled as generic organizational process')
assert.equal(cal10.preconditions.some((item) => !item.basedOnCandidateCode && item.canonicalCategory === 'TIME_PRESSURE'), false)

console.log('PASS human calibration second five regression V2 — communication, objective timing, organization, perception and action knowledge boundaries')
