import assert from 'node:assert/strict'
import { runSeraVNextEngineV0 } from '../../frontend/src/lib/sera-vnext/engine-v0/run-engine'
import type { SeraSemanticEvidenceAnnotation } from '../../frontend/src/lib/sera-vnext/engine-contract'

function run(inputId: string, narrative: string, semanticEvidence: SeraSemanticEvidenceAnnotation[]) {
  return runSeraVNextEngineV0({
    inputId,
    narrative,
    locale: 'pt-BR',
    sourceType: 'real_event',
    requestId: inputId,
    mode: 'CANDIDATE_ONLY',
    semanticEvidence,
    semanticEnrichmentMeta: {
      provider: 'frozen-calibration-semantics',
      model: 'semantic-contract-v2',
      requestedAt: 'frozen',
      acceptedAnnotations: semanticEvidence.length,
      rejectedAnnotations: 0,
      schemaVersion: 'SERA_SEMANTIC_AI_V2',
    },
    options: { allowLlm: true, requireHumanReview: true, includeDebugTrace: true },
  })
}

function a(args: Omit<SeraSemanticEvidenceAnnotation, 'id'> & { id: string }): SeraSemanticEvidenceAnnotation {
  return args
}

const cal01Narrative = 'Durante a preparação para uma decolagem offshore, a tripulação recebeu uma alteração de última hora na sequência de passageiros e bagagens. O copiloto atualizou a documentação e retomou a checklist a partir do ponto em que acreditava ter parado. O item de confirmação do seletor de combustível não foi executado. Após a partida, ainda no táxi, o comandante percebeu que a configuração não correspondia ao previsto e corrigiu antes da decolagem. O copiloto declarou que conhecia o item, que normalmente o executava e que simplesmente não se lembrou de retomá-lo após a interrupção. Não houve falha de indicação do sistema. A mudança de última hora gerou pressão para manter o horário e várias comunicações simultâneas na cabine.'
const cal01 = run('CAL-01-REGRESSION-V2', cal01Narrative, [
  a({ id: 'C01-P', sourceQuote: 'O copiloto atualizou a documentação e retomou a checklist a partir do ponto em que acreditava ter parado.', sourceSentenceIndex: 1, roles: ['PERCEPTION_STATE'], concepts: [], actor: 'copiloto', temporalRelation: 'PRE_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: null, actionFailureMechanism: 'NONE_OR_UNKNOWN', actionMechanismEvidenceQuote: null, displayInterpretation: 'O operador acreditava que a partir do ponto em que acreditava ter parado.', confidence: 'HIGH', rationale: 'Estado percebido contemporâneo à retomada.' }),
  a({ id: 'C01-A', sourceQuote: 'O copiloto atualizou a documentação e retomou a checklist a partir do ponto em que acreditava ter parado.', sourceSentenceIndex: 1, roles: ['ACTION_STRATEGY'], concepts: [], actor: 'copiloto', temporalRelation: 'AT_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: null, actionFailureMechanism: 'NONE_OR_UNKNOWN', actionMechanismEvidenceQuote: null, displayInterpretation: 'O operador tentava atingir o objetivo por meio de retomou a checklist a partir do ponto em que acreditava ter parado.', confidence: 'HIGH', rationale: 'Estratégia de retomada; display propositalmente malformado para testar fallback de apresentação.' }),
  a({ id: 'C01-P-FOCUSED', sourceQuote: 'O copiloto atualizou a documentação e retomou a checklist a partir do ponto em que acreditava ter parado.', sourceSentenceIndex: 1, roles: ['PERCEPTION_STATE'], concepts: [], actor: 'copiloto', temporalRelation: 'PRE_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: null, actionFailureMechanism: 'NONE_OR_UNKNOWN', actionMechanismEvidenceQuote: null, displayInterpretation: 'O operador acreditava ter retomado a checklist a partir do ponto em que havia parado.', confidence: 'HIGH', rationale: 'Passagem focalizada normaliza apenas a apresentação, sem alterar a evidência.' }),
  a({ id: 'C01-A-FOCUSED', sourceQuote: 'O copiloto atualizou a documentação e retomou a checklist a partir do ponto em que acreditava ter parado.', sourceSentenceIndex: 1, roles: ['ACTION_STRATEGY'], concepts: [], actor: 'copiloto', temporalRelation: 'AT_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: null, actionFailureMechanism: 'NONE_OR_UNKNOWN', actionMechanismEvidenceQuote: null, displayInterpretation: 'O operador tentava retomar a checklist a partir do ponto em que acreditava ter parado.', confidence: 'HIGH', rationale: 'Passagem focalizada produz frase de apresentação gramatical.' }),
  a({ id: 'C01-AUDIT', sourceQuote: 'O item de confirmação do seletor de combustível não foi executado.', sourceSentenceIndex: 2, roles: ['ACTION_MECHANISM'], concepts: [], actor: 'copiloto', temporalRelation: 'AT_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: null, actionFailureMechanism: 'PROCEDURAL_OMISSION', actionMechanismEvidenceQuote: 'O item de confirmação do seletor de combustível não foi executado.', displayInterpretation: null, confidence: 'HIGH', rationale: 'Auditoria semântica independente: omissão procedural explícita.' }),
  a({ id: 'C01-FIRST', sourceQuote: 'O item de confirmação do seletor de combustível não foi executado.', sourceSentenceIndex: 2, roles: ['FIRST_DEPARTURE', 'CRITICAL_UNSAFE_ACT', 'DIRECT_ACTOR', 'ACTION_STRATEGY'], concepts: ['slipLapse', 'proceduralOmission'], actor: 'copiloto', temporalRelation: 'AT_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: null, actionFailureMechanism: 'PROCEDURAL_OMISSION', actionMechanismEvidenceQuote: 'O item de confirmação do seletor de combustível não foi executado.', confidence: 'HIGH', rationale: 'O relato atribui a omissão ao copiloto por correferência explícita.' }),
  a({ id: 'C01-PC-TIME', sourceQuote: 'A mudança de última hora gerou pressão para manter o horário e várias comunicações simultâneas na cabine.', sourceSentenceIndex: 6, roles: ['PRECONDITION'], concepts: ['timeManagementPressure'], actor: null, temporalRelation: 'PRE_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: 'TIME_PRESSURE', preconditionCausalStatus: 'PRESENT_CONTEXT', confidence: 'HIGH', rationale: 'Pressão operacional presente; nexo causal não declarado.' }),
  a({ id: 'C01-PC-ATTN', sourceQuote: 'A mudança de última hora gerou pressão para manter o horário e várias comunicações simultâneas na cabine.', sourceSentenceIndex: 6, roles: ['PRECONDITION'], concepts: ['attentionPressure'], actor: null, temporalRelation: 'PRE_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: 'PRESENT_CONTEXT', confidence: 'MEDIUM', rationale: 'Demandas simultâneas/carga atencional presentes; sem forçar categoria canônica.' }),
])
assert.equal(cal01.escapePoint.firstDepartureCandidate, 'O item de confirmação do seletor de combustível não foi executado.')
assert.equal(cal01.directActor.actor, 'copiloto')
assert.equal(cal01.axes.action.proposedCode, 'A-B')
assert.equal(cal01.axes.objective.proposedCode, null)
assert.match(cal01.canonicalTraversal.paths.find((path) => path.axis === 'P')?.answers[0]?.responseText ?? '', /acreditava ter retomado a checklist/i)
assert.match(cal01.canonicalTraversal.paths.find((path) => path.axis === 'A')?.answers[0]?.responseText ?? '', /tentava retomar a checklist/i)
assert.doesNotMatch(cal01.canonicalTraversal.paths.find((path) => path.axis === 'A')?.answers[0]?.responseText ?? '', /por meio de retomou/i)
assert.ok(cal01.preconditions.some((item) => item.canonicalCategory === 'TIME_PRESSURE' && !item.basedOnCandidateCode && item.evidence.length > 0))
assert.ok(cal01.preconditions.some((item) => item.category === 'ATTENTION_WORKLOAD_CONTEXT' && item.canonicalCategory === null && !item.basedOnCandidateCode && item.evidence.length > 0))
assert.equal(cal01.preconditions.filter((item) => !item.basedOnCandidateCode).every((item) => item.relationship === 'UNRELATED_OR_UNSUPPORTED'), true, 'present context is not causality')

const cal02Narrative = 'Em uma aproximação para uma plataforma, ocorreram dois momentos distintos de saída da operação segura. Primeiro, ao configurar a automação para a descida, o piloto selecionou um modo diferente daquele que pretendia, apesar de os modos disponíveis e suas indicações estarem normais. O desvio foi percebido pelo outro piloto e corrigido. Alguns minutos depois, já estabilizada a aproximação, a tripulação interrompeu a checklist para responder a uma chamada operacional. Ao retomá-la, um item de confirmação de configuração não foi executado e só foi identificado após o pouso. Os depoimentos distinguem claramente os dois momentos e indicam mecanismos diferentes: uma seleção incorreta entre alternativas no primeiro e uma omissão de etapa no segundo.'
const cal02 = run('CAL-02-REGRESSION-V2', cal02Narrative, [
  a({ id: 'C02-AUDIT', sourceQuote: 'o piloto selecionou um modo diferente daquele que pretendia', sourceSentenceIndex: 1, roles: ['ACTION_MECHANISM'], concepts: [], actor: 'piloto', temporalRelation: 'AT_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: null, actionFailureMechanism: 'IMPLEMENTATION_MISMATCH', actionMechanismEvidenceQuote: 'o piloto selecionou um modo diferente daquele que pretendia', displayInterpretation: null, confidence: 'HIGH', rationale: 'Auditoria semântica independente: implementação diferente da intenção.' }),
  a({ id: 'C02-A-FOCUSED', sourceQuote: 'ao configurar a automação para a descida', sourceSentenceIndex: 1, roles: ['ACTION_STRATEGY'], concepts: [], actor: 'piloto', temporalRelation: 'AT_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: null, actionFailureMechanism: 'NONE_OR_UNKNOWN', actionMechanismEvidenceQuote: null, displayInterpretation: 'O piloto tentava configurar a automação para a descida.', confidence: 'HIGH', rationale: 'Estratégia separada do mecanismo de falha.' }),
  a({ id: 'C02-FIRST', sourceQuote: 'o piloto selecionou um modo diferente daquele que pretendia', sourceSentenceIndex: 1, roles: ['FIRST_DEPARTURE', 'CRITICAL_UNSAFE_ACT', 'DIRECT_ACTOR', 'ACTION_STRATEGY'], concepts: ['slipLapse', 'implementationMismatch', 'implementedAction'], actor: 'piloto', temporalRelation: 'AT_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: null, actionFailureMechanism: 'IMPLEMENTATION_MISMATCH', actionMechanismEvidenceQuote: 'o piloto selecionou um modo diferente daquele que pretendia', confidence: 'HIGH', rationale: 'Seleção implementada diferiu da intenção.' }),
  a({ id: 'C02-LATER', sourceQuote: 'um item de confirmação de configuração não foi executado', sourceSentenceIndex: 4, roles: ['CRITICAL_UNSAFE_ACT'], concepts: ['slipLapse'], actor: null, temporalRelation: 'POST_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: null, confidence: 'HIGH', rationale: 'Segundo desvio humano, posterior e distinto.' }),
])
assert.equal(cal02.escapePoint.firstDepartureCandidate, 'o piloto selecionou um modo diferente daquele que pretendia')
assert.equal(cal02.escapePoint.criticalUnsafeActCandidate, 'um item de confirmação de configuração não foi executado')
assert.equal(cal02.escapePoint.anchorBasis, 'FIRST_DEPARTURE_PRIMARY')
assert.equal(cal02.directActor.actor, 'piloto')
assert.equal(cal02.axes.action.proposedCode, 'A-B')
assert.equal(cal02.axes.objective.proposedCode, null)
assert.match(cal02.canonicalTraversal.paths.find((path) => path.axis === 'A')?.answers[0]?.responseText ?? '', /tentava configurar a automa[cç][aã]o para a descida/i)
assert.doesNotMatch(cal02.canonicalTraversal.paths.find((path) => path.axis === 'A')?.answers[0]?.responseText ?? '', /^o piloto selecionou um modo diferente/i)
for (const axis of [cal02.axes.perception, cal02.axes.objective, cal02.axes.action]) {
  assert.equal(axis.supportingEvidence.some((text) => /item de confirma[cç][aã]o de configura[cç][aã]o/i.test(text)), false, 'later omission must not contaminate first-departure P/O/A')
}

const cal03Narrative = 'Durante uma aproximação offshore em condições de alta carga de trabalho, a tripulação recebeu uma mudança tardia de proa e uma solicitação simultânea de coordenação. Nesse período, o piloto monitorando deixou de acompanhar uma indicação que permanecia disponível e, logo depois, o piloto voando selecionou uma configuração inadequada entre duas alternativas conhecidas. A indicação estava legível e não havia falha técnica. A seleção incorreta não decorreu de desconhecimento do sistema: o piloto descreveu corretamente, após o evento, a função de cada alternativa. Os dois desvios foram detectados por barreiras diferentes e em momentos diferentes, antes de produzirem consequência operacional.'
const cal03 = run('CAL-03-REGRESSION-V2', cal03Narrative, [
  a({ id: 'C03-AUDIT', sourceQuote: 'o piloto monitorando deixou de acompanhar uma indicação que permanecia disponível', sourceSentenceIndex: 1, roles: ['ACTION_MECHANISM'], concepts: [], actor: 'piloto monitorando (PM)', temporalRelation: 'AT_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: null, actionFailureMechanism: 'MONITORING_ATTENTION_LAPSE', actionMechanismEvidenceQuote: 'o piloto monitorando deixou de acompanhar uma indicação que permanecia disponível', displayInterpretation: null, confidence: 'HIGH', rationale: 'Auditoria semântica independente: falha de monitoramento, sem evidência de implementação.' }),
  a({ id: 'C03-FIRST', sourceQuote: 'o piloto monitorando deixou de acompanhar uma indicação que permanecia disponível', sourceSentenceIndex: 1, roles: ['FIRST_DEPARTURE', 'DIRECT_ACTOR', 'ACTION_STRATEGY'], concepts: ['slipLapse'], actor: 'piloto monitorando (PM)', temporalRelation: 'AT_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: null, actionFailureMechanism: 'PROCEDURAL_OMISSION', actionMechanismEvidenceQuote: 'o piloto monitorando deixou de acompanhar uma indicação que permanecia disponível', confidence: 'HIGH', rationale: 'Primeira passagem semântica propositalmente sobreclassificada; a auditoria independente deve impedir A-B.' }),
  a({ id: 'C03-LATER', sourceQuote: 'o piloto voando selecionou uma configuração inadequada entre duas alternativas conhecidas', sourceSentenceIndex: 1, roles: ['CRITICAL_UNSAFE_ACT', 'DIRECT_ACTOR'], concepts: ['selectionSubtype'], actor: 'piloto voando (PF)', temporalRelation: 'POST_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: null, confidence: 'HIGH', rationale: 'Ato posterior distinto dentro da mesma frase.' }),
  a({ id: 'C03-PC', sourceQuote: 'Durante uma aproximação offshore em condições de alta carga de trabalho, a tripulação recebeu uma mudança tardia de proa e uma solicitação simultânea de coordenação.', sourceSentenceIndex: 0, roles: ['PRECONDITION'], concepts: ['attentionPressure'], actor: null, temporalRelation: 'PRE_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: 'PRESENT_CONTEXT', confidence: 'MEDIUM', rationale: 'Carga atencional presente sem forçar categoria canônica.' }),
  a({ id: 'C03-TIME-OVERCLAIM', sourceQuote: 'uma mudança tardia de proa', sourceSentenceIndex: 0, roles: ['PRECONDITION'], concepts: [], actor: null, temporalRelation: 'PRE_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: 'TIME_PRESSURE', preconditionCausalStatus: 'PRESENT_CONTEXT', confidence: 'MEDIUM', rationale: 'Fixture propositalmente sobreclassificado: cronologia tardia sem restrição temporal operacional.' }),
])
assert.equal(cal03.escapePoint.firstDepartureCandidate, 'o piloto monitorando deixou de acompanhar uma indicação que permanecia disponível')
assert.equal(cal03.escapePoint.criticalUnsafeActCandidate, 'o piloto voando selecionou uma configuração inadequada entre duas alternativas conhecidas')
assert.equal(cal03.escapePoint.anchorBasis, 'FIRST_DEPARTURE_PRIMARY')
assert.equal(cal03.directActor.actor, 'piloto monitorando (PM)')
assert.equal(cal03.escapePoint.criticalUnsafeActActor, 'piloto voando (PF)')
assert.equal(cal03.axes.action.proposedCode, null, 'monitoring discontinuity alone must not be promoted to A-B by a generic slip/lapse label')
for (const axis of [cal03.axes.perception, cal03.axes.objective, cal03.axes.action]) {
  assert.equal(axis.supportingEvidence.some((text) => /piloto voando selecionou/i.test(text)), false)
}
assert.ok(cal03.preconditions.some((item) => item.category === 'ATTENTION_WORKLOAD_CONTEXT' && item.canonicalCategory === null && !item.basedOnCandidateCode))
assert.equal(cal03.preconditions.some((item) => !item.basedOnCandidateCode && item.canonicalCategory === 'TIME_PRESSURE'), false, 'chronological lateness alone must not create TIME_PRESSURE without the semantic timeManagementPressure signal')

const al04Narrative = 'Em um voo de transporte offshore, um item de preparação foi omitido e a aeronave iniciou uma etapa com uma configuração que precisou ser corrigida logo após a decolagem. A investigação identificou que o tripulante estava no fim de uma sequência intensa de jornadas e relatou cansaço. Na cabine, o outro piloto percebeu que a preparação estava acelerada, mas não interrompeu a sequência porque havia forte gradiente de autoridade. O supervisor de operações havia solicitado prioridade para recuperar atrasos acumulados e não reavaliou a carga de trabalho da tripulação. A programação daquele dia fora montada sem margem para atrasos e sem tripulação reserva disponível, embora a área já tivesse registrado dificuldades recorrentes de recuperação de escala. Não houve defeito técnico na aeronave.'
const al04 = run('AL-04-REGRESSION-V2', al04Narrative, [
  a({ id: 'A04-FIRST', sourceQuote: 'um item de preparação foi omitido', sourceSentenceIndex: 0, roles: ['FIRST_DEPARTURE'], concepts: ['slipLapse'], actor: null, temporalRelation: 'AT_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: null, actionFailureMechanism: 'PROCEDURAL_OMISSION', actionMechanismEvidenceQuote: 'um item de preparação foi omitido', confidence: 'HIGH', rationale: 'Omissão passiva sem executor identificado.' }),
  a({ id: 'A04-LATER', sourceQuote: 'a aeronave iniciou uma etapa com uma configuração que precisou ser corrigida logo após a decolagem', sourceSentenceIndex: 0, roles: ['CRITICAL_UNSAFE_ACT'], concepts: [], actor: null, temporalRelation: 'POST_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: null, confidence: 'MEDIUM', rationale: 'Condição operacional posterior distinta.' }),
  a({ id: 'A04-PHYS', sourceQuote: 'A investigação identificou que o tripulante estava no fim de uma sequência intensa de jornadas e relatou cansaço.', sourceSentenceIndex: 1, roles: ['PRECONDITION'], concepts: [], actor: null, temporalRelation: 'PRE_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: 'PHYSIOLOGICAL', preconditionCausalStatus: 'PRESENT_CONTEXT', confidence: 'HIGH', rationale: 'Fator fisiológico presente; ator da falha não resolvido.' }),
  a({ id: 'A04-SOC', sourceQuote: 'Na cabine, o outro piloto percebeu que a preparação estava acelerada, mas não interrompeu a sequência porque havia forte gradiente de autoridade.', sourceSentenceIndex: 2, roles: ['PRECONDITION'], concepts: [], actor: 'outro piloto', temporalRelation: 'PRE_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: 'SOCIAL', preconditionCausalStatus: 'PRESENT_CONTEXT', confidence: 'HIGH', rationale: 'Gradiente de autoridade explicitamente presente.' }),
  a({ id: 'A04-SUP', sourceQuote: 'O supervisor de operações havia solicitado prioridade para recuperar atrasos acumulados e não reavaliou a carga de trabalho da tripulação.', sourceSentenceIndex: 3, roles: ['PRECONDITION'], concepts: [], actor: 'supervisor de operações', temporalRelation: 'PRE_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: 'MONITORING_SUPERVISION', preconditionCausalStatus: 'PRESENT_CONTEXT', confidence: 'HIGH', rationale: 'Supervisão contextual.' }),
  a({ id: 'A04-TIME', sourceQuote: 'O supervisor de operações havia solicitado prioridade para recuperar atrasos acumulados e não reavaliou a carga de trabalho da tripulação.', sourceSentenceIndex: 3, roles: ['PRECONDITION'], concepts: ['timeManagementPressure'], actor: 'supervisor de operações', temporalRelation: 'PRE_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: 'TIME_PRESSURE', preconditionCausalStatus: 'PRESENT_CONTEXT', confidence: 'HIGH', rationale: 'Pressão temporal contextual.' }),
  a({ id: 'A04-RES', sourceQuote: 'A programação daquele dia fora montada sem margem para atrasos e sem tripulação reserva disponível, embora a área já tivesse registrado dificuldades recorrentes de recuperação de escala.', sourceSentenceIndex: 4, roles: ['PRECONDITION'], concepts: [], actor: null, temporalRelation: 'PRE_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: 'PROVISION_RESOURCES', preconditionCausalStatus: 'PRESENT_CONTEXT', confidence: 'HIGH', rationale: 'Recursos/contexto organizacional.' }),
  a({ id: 'A04-OVER', sourceQuote: 'A programação daquele dia fora montada sem margem para atrasos e sem tripulação reserva disponível, embora a área já tivesse registrado dificuldades recorrentes de recuperação de escala.', sourceSentenceIndex: 4, roles: ['PRECONDITION'], concepts: [], actor: null, temporalRelation: 'PRE_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: 'OVERSIGHT', preconditionCausalStatus: 'PRESENT_CONTEXT', confidence: 'MEDIUM', rationale: 'Dificuldade recorrente preservada para revisão.' }),
])
assert.equal(al04.escapePoint.firstDepartureCandidate, 'um item de preparação foi omitido')
assert.equal(al04.escapePoint.criticalUnsafeActCandidate, 'a aeronave iniciou uma etapa com uma configuração que precisou ser corrigida logo após a decolagem')
assert.equal(al04.directActor.status, 'AMBIGUOUS')
assert.equal(al04.directActor.actor, null)
assert.equal(al04.escapePoint.firstDepartureActor, null)
assert.equal(al04.canonicalTraversal.paths.length, 0)
for (const canonical of ['PHYSIOLOGICAL', 'SOCIAL', 'TIME_PRESSURE', 'MONITORING_SUPERVISION', 'PROVISION_RESOURCES', 'OVERSIGHT'] as const) {
  const pc = al04.preconditions.find((item) => item.canonicalCategory === canonical)
  assert.ok(pc, `${canonical} must remain visible because it is semantically source-grounded`)
  assert.equal(pc?.basedOnCandidateCode, false)
  assert.equal(pc?.methodologyMatch, 'HYPOTHESIS_ONLY')
  assert.equal(pc?.relationship, 'UNRELATED_OR_UNSUPPORTED')
}

const al05Narrative = 'No terceiro setor de um dia operacional prolongado, o copiloto omitiu uma etapa rotineira da checklist de pós-pouso. O item só foi percebido durante a preparação para o setor seguinte. Ele afirmou conhecer perfeitamente o procedimento e não relatou dúvida sobre a ação correta. Na entrevista, informou ter dormido cerca de quatro horas na noite anterior, ter iniciado a apresentação muito cedo e sentir sonolência desde o segundo setor. O comandante confirmou bocejos frequentes e redução do ritmo de resposta. Não havia pressão temporal relevante naquele momento, nem falha de equipamento ou informação ambígua. O evento não produziu dano e a configuração foi regularizada antes do próximo voo.'
const al05 = run('AL-05-REGRESSION-V2', al05Narrative, [
  a({ id: 'A05-AUDIT', sourceQuote: 'o copiloto omitiu uma etapa rotineira da checklist de pós-pouso', sourceSentenceIndex: 0, roles: ['ACTION_MECHANISM'], concepts: [], actor: 'copiloto', temporalRelation: 'AT_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: null, actionFailureMechanism: 'PROCEDURAL_OMISSION', actionMechanismEvidenceQuote: 'o copiloto omitiu uma etapa rotineira da checklist de pós-pouso', displayInterpretation: null, confidence: 'HIGH', rationale: 'Auditoria semântica independente: omissão procedural explícita.' }),
  a({ id: 'A05-FIRST', sourceQuote: 'o copiloto omitiu uma etapa rotineira da checklist de pós-pouso', sourceSentenceIndex: 0, roles: ['FIRST_DEPARTURE', 'CRITICAL_UNSAFE_ACT', 'DIRECT_ACTOR', 'ACTION_STRATEGY'], concepts: ['slipLapse', 'proceduralOmission'], actor: 'copiloto', temporalRelation: 'AT_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: null, preconditionCausalStatus: null, actionFailureMechanism: 'PROCEDURAL_OMISSION', actionMechanismEvidenceQuote: 'o copiloto omitiu uma etapa rotineira da checklist de pós-pouso', confidence: 'HIGH', rationale: 'Omissão procedural pelo copiloto.' }),
  a({ id: 'A05-PHYS1', sourceQuote: 'Na entrevista, informou ter dormido cerca de quatro horas na noite anterior, ter iniciado a apresentação muito cedo e sentir sonolência desde o segundo setor.', sourceSentenceIndex: 3, roles: ['PRECONDITION'], concepts: [], actor: 'copiloto', temporalRelation: 'PRE_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: 'PHYSIOLOGICAL', preconditionCausalStatus: 'PRESENT_CONTEXT', confidence: 'HIGH', rationale: 'Restrição de sono e sonolência explicitamente presentes; nexo causal não declarado.' }),
  a({ id: 'A05-PHYS2', sourceQuote: 'O comandante confirmou bocejos frequentes e redução do ritmo de resposta.', sourceSentenceIndex: 4, roles: ['PRECONDITION'], concepts: [], actor: 'copiloto', temporalRelation: 'PRE_ESCAPE', assertionStatus: 'AFFIRMED', occurrenceScope: 'CURRENT_EVENT', preconditionCategory: 'PHYSIOLOGICAL', preconditionCausalStatus: 'PRESENT_CONTEXT', confidence: 'HIGH', rationale: 'Sinais comportamentais observados; nexo causal não declarado.' }),
])
assert.equal(al05.directActor.actor, 'copiloto')
assert.equal(al05.axes.action.proposedCode, 'A-B')
assert.equal(al05.axes.objective.proposedCode, null)
assert.match(al05.canonicalTraversal.paths.find((path) => path.axis === 'A')?.answers[0]?.responseText ?? '', /estrat[eé]gia n[aã]o est[aá] descrita.*omiss[aã]o.*etapa procedural/i)
const physiological = al05.preconditions.find((item) => item.canonicalCategory === 'PHYSIOLOGICAL' && !item.basedOnCandidateCode)
assert.ok(physiological, 'semantic physiological evidence must be preserved regardless of lexical wording')
assert.equal(physiological?.relationship, 'UNRELATED_OR_UNSUPPORTED', 'physiological facts do not become causal until the source explicitly links them to the active failure')
assert.equal(physiological?.methodologyMatch, 'HYPOTHESIS_ONLY')
assert.match(physiological?.evidence.join(' ') ?? '', /quatro horas.*sonol[eê]ncia|bocejos.*redu[cç][aã]o do ritmo/i)
assert.equal(al05.preconditions.some((item) => !item.basedOnCandidateCode && item.canonicalCategory === 'TIME_PRESSURE'), false, 'explicit absence of time pressure must not be converted into a positive factor')

for (const output of [cal01, cal02, al05]) {
  const taxonomyOnly = output.preconditions.filter((item) => item.basedOnCandidateCode && item.evidence.length === 0)
  assert.ok(taxonomyOnly.length > 0, 'Table 1 routes remain investigation guidance after an A-B candidate')
  assert.equal(taxonomyOnly.every((item) => item.methodologyMatch === 'HYPOTHESIS_ONLY' && item.relationship === 'UNRELATED_OR_UNSUPPORTED'), true)
}

console.log('PASS human calibration first five regression V2 — AI semantics feed deterministic SERA locks without case-specific language rules')
