import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { computeCandidateAttention, directActorStatusLabel, friendlyAnswerLabel, friendlyNodeLabel } from '../../frontend/src/lib/sera-vnext/presentation'

const root = path.resolve(__dirname, '..', '..')

assert.equal(friendlyNodeLabel('P_ASSESSMENT', true), 'Avaliação da situação')
assert.equal(friendlyNodeLabel('P_TIME_PRESSURE', true), 'Pressão de tempo')
assert.equal(friendlyNodeLabel('A_IMPLEMENTED', true), 'Execução da ação')
assert.equal(friendlyAnswerLabel('START', true), 'Resposta descritiva')
assert.equal(friendlyAnswerLabel('NÃO', true), 'Não')
assert.equal(directActorStatusLabel({ actor: 'copiloto', status: 'IDENTIFIED', alternatives: [], actorMigrationWarnings: [] }, true), 'Identificado')
assert.equal(directActorStatusLabel({ actor: null, status: 'AMBIGUOUS', alternatives: [], actorMigrationWarnings: [] }, true), 'Não resolvido')
assert.equal(directActorStatusLabel({ actor: 'flight crew (collective)', status: 'AMBIGUOUS', alternatives: ['comandante', 'copiloto'], actorMigrationWarnings: [] }, true), 'Ambíguo — requer decomposição')
assert.equal(directActorStatusLabel({ actor: null, status: 'NOT_APPLICABLE', alternatives: [], actorMigrationWarnings: [] }, true), 'Não aplicável')

const candidate = computeCandidateAttention('P-G', 'O-A', 'A-A')
assert.ok(candidate)
assert.equal(candidate?.score, 42)
assert.deepEqual(candidate?.activeAxes, ['P'])
const screenReport = fs.readFileSync(path.join(root, 'frontend/src/app/(dashboard)/reports/event/[id]/page.tsx'), 'utf8')
const serverPdf = fs.readFileSync(path.join(root, 'frontend/src/lib/sera-vnext-product/pdf-report.ts'), 'utf8')
const eventPanel = fs.readFileSync(path.join(root, 'frontend/src/components/sera-vnext/VNextEventAnalysisPanel.tsx'), 'utf8')
const reportsIndex = fs.readFileSync(path.join(root, 'frontend/src/app/(dashboard)/reports/page.tsx'), 'utf8')

assert.equal(screenReport.includes("analysis?.event_summary ?? eventData?.raw_input"), false)
assert.equal(serverPdf.includes("body(doc, analysis.narrative"), false)
assert.ok(screenReport.includes('Resumo técnico'))
assert.ok(screenReport.includes('Como o sistema chegou à classificação'))
assert.ok(screenReport.includes('CanonicalTreeDiagram'))
assert.ok(screenReport.includes('Pré-condições sustentadas pela evidência'))
assert.ok(screenReport.includes('Hipóteses preservadas — não confirmadas causalmente'))
assert.ok(serverPdf.includes("L('Resumo executivo', 'Executive summary')"))
assert.ok(serverPdf.includes("L('Pré-condições sustentadas pela evidência', 'Preconditions supported by the evidence')"))
assert.ok(serverPdf.includes("L('Hipóteses preservadas - não confirmadas causalmente', 'Retained hypotheses - not causally confirmed')"))
assert.ok(serverPdf.includes('postEscapeStatements'))
assert.ok(serverPdf.includes("L('Fatos-chave utilizados na análise', 'Key facts used in the analysis')"))
assert.ok(serverPdf.includes("L('Episódio operacional reconstruído ao redor do ponto de fuga', 'Operational episode reconstructed around the escape point')"))
assert.ok(serverPdf.includes('historicalComparators'))
assert.ok(serverPdf.includes("L('Outras sequências humanas/contextuais detectadas — não são pontos de fuga automáticos', 'Other human/contextual sequences detected — not automatic escape points')"))
assert.ok(serverPdf.includes("L('Gate de âncora de Fatores Humanos', 'Human-Factor anchor gate')"))
assert.ok(serverPdf.includes('renderCanonicalTreePage'))
assert.ok(serverPdf.includes('doc.polygon('))
assert.ok(serverPdf.includes('A Tabela 1 de Hendy e o Anexo B'))
assert.ok(serverPdf.includes('buildSeraHfacsBridge'))
assert.ok(serverPdf.includes('SERA_PRECONDITION_META'))
assert.ok(serverPdf.includes('Commit da execução da análise'))
assert.ok(serverPdf.includes('Commit do runtime que gerou este relatório'))
assert.ok(serverPdf.includes('Fonte do commit do runtime'))
assert.ok(serverPdf.includes('Vercel deployment ID'))
assert.ok(serverPdf.includes('Outros fatores contribuintes e observações operacionais'))
assert.equal(serverPdf.includes("L('Barreiras e observações operacionais', 'Operational barriers and observations')"), false)
assert.ok(serverPdf.includes('const h = isTerminal ? 40'))
assert.ok(serverPdf.includes('height: 23'))
assert.ok(serverPdf.includes('Trajetória percorrida'))
assert.ok(screenReport.includes('dimensões padronizadas'))
assert.ok(screenReport.includes('Correspondência SERA / HFACS'))
assert.equal(screenReport.includes('bg-slate-950 p-3'), false)
assert.ok(screenReport.includes('node.responseText'))
const canonicalFlow = fs.readFileSync(path.join(root, 'frontend/src/lib/sera-vnext/canonical-flow-visual.ts'), 'utf8')
assert.equal(canonicalFlow.includes('fill:#111827'), false)
assert.equal(canonicalFlow.includes('fill:#0f172a'), false)
assert.ok(canonicalFlow.includes('Full canonical question + answer'))
assert.ok(serverPdf.includes('pathAnswerText'))
assert.equal(serverPdf.includes("L('Resposta: ', 'Answer: ') + friendlyAnswerLabel(node.answer, pt)"), false)
assert.ok(screenReport.includes('Tabela 1 de Hendy'))
assert.ok(serverPdf.includes('Topologia canônica preservada'))
assert.ok(serverPdf.includes("L('Apêndice técnico - rastreabilidade e auditoria'"))
assert.ok(eventPanel.includes('CanonicalDecisionJourney'))
assert.ok(eventPanel.includes('CandidateRiskCard'))
for (const source of [screenReport, serverPdf, eventPanel]) {
  assert.ok(source.includes("item.evidenceType !== 'NON_CAUSAL_DOCUMENT'"))
  assert.ok(source.includes("item.evidenceType !== 'SYSTEM_DESCRIPTION'"))
  assert.ok(source.includes('item.statement.length <= 1200'))
}
assert.ok(reportsIndex.includes("redirect('/reports/executive')"))
assert.ok(screenReport.includes('travessia canônica P/O/A não foi iniciada'))
assert.ok(serverPdf.includes('A travessia canônica P/O/A não foi iniciada'))
assert.ok(serverPdf.includes('Consequência não utilizada como causa'))
assert.ok(serverPdf.includes('directActorStatusLabel(output.directActor, pt)'))
assert.ok(screenReport.includes('directActorStatusLabel(vnextOutput.directActor'))
assert.ok(eventPanel.includes('directActorStatusLabel(output.directActor, pt)'))
assert.ok(serverPdf.includes('Nenhuma migração indevida do ator causal'))
assert.ok(serverPdf.includes("L('Motor SERA (runtime)', 'SERA engine (runtime)')"))
const versioning = fs.readFileSync(path.join(root, 'frontend/src/lib/sera-vnext-product/versioning.ts'), 'utf8')
assert.ok(versioning.includes('SERA_CODE_COMMIT'))

console.log('PASS report presentation and didactic flow')
