import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { computeCandidateAttention, directActorStatusLabel, friendlyAnswerLabel, friendlyNodeLabel, hfacsBridgeLevelLabel, preconditionLevelLabel, preconditionMethodologyMatchLabel } from '../../frontend/src/lib/sera-vnext/presentation'

const root = path.resolve(__dirname, '..', '..')

assert.equal(friendlyNodeLabel('P_ASSESSMENT', true), 'Avaliação da situação')
assert.equal(friendlyNodeLabel('P_TIME_PRESSURE', true), 'Pressão de tempo')
assert.equal(friendlyNodeLabel('A_IMPLEMENTED', true), 'Execução da ação')
assert.equal(friendlyAnswerLabel('START', true), 'Resposta descritiva')
assert.equal(friendlyAnswerLabel('NÃO', true), 'Não')
assert.equal(preconditionMethodologyMatchLabel('EVIDENCED_OUTSIDE_MOST_LIKELY_SET', true), 'Sustentada pela evidência fora do conjunto mais provável da tabela')
assert.equal(preconditionLevelLabel('IMMEDIATE', true), 'Imediato')
assert.equal(hfacsBridgeLevelLabel('PRECONDITION', true), 'Pré-condição')
assert.equal(directActorStatusLabel({ actor: 'copiloto', status: 'IDENTIFIED', alternatives: [], actorMigrationWarnings: [] }, true), 'Identificado')
assert.equal(directActorStatusLabel({ actor: null, status: 'AMBIGUOUS', alternatives: [], actorMigrationWarnings: [] }, true), 'Não resolvido')
assert.equal(directActorStatusLabel({ actor: 'flight crew (collective)', status: 'AMBIGUOUS', alternatives: ['comandante', 'copiloto'], actorMigrationWarnings: [] }, true), 'Ambíguo — requer decomposição')
assert.equal(directActorStatusLabel({ actor: null, status: 'NOT_APPLICABLE', alternatives: [], actorMigrationWarnings: [] }, true), 'Não aplicável')

const candidate = computeCandidateAttention('P-G', 'O-A', 'A-A')
assert.ok(candidate)
assert.equal(candidate?.score, 42)
assert.deepEqual(candidate?.activeAxes, ['P'])
const screenReport = fs.readFileSync(path.join(root, 'frontend/src/app/(dashboard)/reports/event/[id]/page.tsx'), 'utf8')
const serverPdf = fs.readFileSync(path.join(root, 'frontend/src/lib/sera-vnext-product/pdf-report.ts'), 'utf8')
const eventPanel = fs.readFileSync(path.join(root, 'frontend/src/components/sera-vnext/VNextEventAnalysisPanel.tsx'), 'utf8')
const canonicalJourney = fs.readFileSync(path.join(root, 'frontend/src/components/sera-vnext/CanonicalDecisionJourney.tsx'), 'utf8')
const reportsIndex = fs.readFileSync(path.join(root, 'frontend/src/app/(dashboard)/reports/page.tsx'), 'utf8')

assert.equal(screenReport.includes("analysis?.event_summary ?? eventData?.raw_input"), false)
assert.equal(serverPdf.includes("body(doc, analysis.narrative"), false)
assert.ok(screenReport.includes('Resumo técnico'))
assert.ok(screenReport.includes('Como o sistema chegou à classificação'))
assert.ok(screenReport.includes('CanonicalTreeDiagram'))
assert.ok(screenReport.includes('Pré-condições sustentadas pela evidência'))
assert.ok(screenReport.includes('Hipóteses preservadas — não confirmadas causalmente'))
assert.ok(serverPdf.includes("L('Síntese executiva', 'Executive summary')"))
assert.ok(serverPdf.includes("L('Linha causal e marcos Hendy', 'Causal line and Hendy landmarks')"))
assert.ok(serverPdf.includes('renderAxisDidacticPage'))
assert.ok(serverPdf.includes("L('Pré-condições sustentadas pela evidência', 'Preconditions supported by the evidence')"))
assert.ok(serverPdf.includes("L('Hipóteses preservadas - não confirmadas causalmente', 'Retained hypotheses - not causally confirmed')"))
assert.ok(serverPdf.includes('buildSeraHfacsBridge'))
assert.ok(serverPdf.includes('SERA_PRECONDITION_META'))
assert.ok(serverPdf.includes("L('Outros fatores contribuintes e observações operacionais', 'Other contributory factors and operational observations')"))
assert.equal(serverPdf.includes("L('Barreiras e observações operacionais', 'Operational barriers and observations')"), false)
assert.ok(serverPdf.includes("L('Apêndice técnico - rastreabilidade e auditoria', 'Technical appendix - traceability and audit')"))
assert.ok(serverPdf.includes("L('Árvores canônicas completas', 'Full canonical trees')"))
assert.ok(serverPdf.includes("L('Rastreabilidade e evidência por nó', 'Node traceability and evidence')"))
assert.ok(serverPdf.includes("L('Delimitação do ponto de fuga e fronteira causal', 'Escape-point and causal-boundary audit')"))
assert.ok(serverPdf.includes("L('Rastreabilidade integral das pré-condições', 'Full precondition traceability')"))
assert.ok(serverPdf.includes("L('Gate de âncora de Fatores Humanos', 'Human-Factor anchor gate')"))
assert.ok(serverPdf.includes('renderCanonicalTreePage'))
assert.ok(serverPdf.includes('doc.polygon('))
assert.ok(serverPdf.includes('pathAnswerText'))
assert.ok(serverPdf.includes('applyPageChrome'))
assert.ok(serverPdf.includes('fontSize(10.5)'), 'main body typography should use the redesigned reading size')
assert.ok(serverPdf.includes("layout: 'landscape'"), 'full canonical trees should move to landscape appendix pages')
assert.ok(serverPdf.includes('Commit da execução da análise'))
assert.ok(serverPdf.includes('Commit do runtime que gerou este relatório'))
assert.ok(serverPdf.includes('Fonte do commit do runtime'))
assert.ok(serverPdf.includes('Vercel deployment ID'))
assert.ok(serverPdf.includes('preconditionMethodologyMatchLabel'))
assert.ok(serverPdf.includes('preconditionLevelLabel'))
assert.ok(serverPdf.includes("item.sourceSection !== 'RECOMMENDATION'"))
assert.ok(serverPdf.includes("item.occurrenceScope !== 'HISTORICAL_COMPARATOR'"))
assert.ok(serverPdf.includes('Hipóteses/afirmações incertas do relatório-fonte'))
assert.ok(serverPdf.includes('não são incertezas do motor'))
assert.ok(serverPdf.includes('Consequência não utilizada como causa'))
assert.equal(serverPdf.includes("L('Resposta: ', 'Answer: ') + friendlyAnswerLabel(node.answer, pt)"), false)
assert.ok(eventPanel.includes('CanonicalDecisionJourney'))
assert.ok(eventPanel.includes('CandidateRiskCard'))
assert.ok(canonicalJourney.includes('node.responseText ?? friendlyAnswerLabel(node.answer, pt)'), 'UI must show the substantive root response instead of the internal INSUFFICIENT_EVIDENCE/START label')
assert.ok(eventPanel.includes("'Resposta inicial SERA'"), 'axis card must distinguish observed action from the initial SERA plan/strategy answer')
for (const source of [screenReport, serverPdf, eventPanel]) {
  assert.ok(source.includes("item.evidenceType !== 'NON_CAUSAL_DOCUMENT'"))
  assert.ok(source.includes("item.evidenceType !== 'SYSTEM_DESCRIPTION'"))
  assert.ok(source.includes('item.statement.length <= 1200'))
}
assert.ok(reportsIndex.includes("redirect('/reports/executive')"))
assert.ok(screenReport.includes('travessia canônica P/O/A não foi iniciada'))
assert.ok(serverPdf.includes('Consequência não utilizada como causa'))
assert.ok(screenReport.includes('directActorStatusLabel(vnextOutput.directActor'))
assert.ok(eventPanel.includes('directActorStatusLabel(output.directActor, pt)'))
assert.ok(serverPdf.includes('Nenhuma migração indevida do ator causal'))
assert.ok(serverPdf.includes("L('Motor SERA (runtime)', 'SERA engine (runtime)')"))
const versioning = fs.readFileSync(path.join(root, 'frontend/src/lib/sera-vnext-product/versioning.ts'), 'utf8')
assert.ok(versioning.includes('SERA_CODE_COMMIT'))

console.log('PASS report presentation and didactic flow')
