#!/usr/bin/env npx tsx
import { basename, join } from 'node:path'
import { existsSync, readdirSync, readFileSync } from 'node:fs'

type Axis='perception'|'objective'|'action'
type A={score:boolean;status:'code'|'unresolved'|'not_scored';code?:string|null}
type Side=Record<Axis,A>
type Pair={caseId:string;scientificUse:boolean;caseRole:string;developmentExposure:boolean;human:Side;humanB?:Side|null;vnext:Side}
const AXES:Axis[]=['perception','objective','action']

function inputDir(){const a=process.argv.slice(2);const i=a.indexOf('--input');return i>=0&&a[i+1]?a[i+1]:'docs/hfa-backlog/naturalistic-kit/fixtures'}
function value(a:A):string|null{if(!a.score||a.status==='not_scored')return null;if(a.status==='unresolved')return 'UNRESOLVED';return a.code??null}
function load(dir:string):Pair[]{if(!existsSync(dir))return[];return readdirSync(dir).filter(f=>f.endsWith('.json')).flatMap(f=>{const raw=JSON.parse(readFileSync(join(dir,f),'utf8'));if(raw.schemaVersion!=='NATURALISTIC_DESCRIPTIVE_PAIR_V2')return[];if(raw.scientificUse===true&&(basename(f).startsWith('TEST_')||String(raw.caseId).startsWith('TEST_')))throw new Error(`SCIENTIFIC_USE_FORBIDDEN_ON_TEST ${f}`);if(raw.scientificUse===true&&(raw.caseRole!=='sealed_holdout'||raw.developmentExposure!==false))throw new Error(`SCIENTIFIC_USE_REQUIRES_SEALED_UNEXPOSED ${f}`);return[raw as Pair]})}
function stats(ps:Pair[],axis:Axis,left:'human'|'humanB',right:'vnext'|'humanB'){let n=0,agree=0,unresolvedAgree=0;const matrix:Record<string,Record<string,number>>={};for(const p of ps){const l=value(left==='human'?p.human[axis]:p.humanB?.[axis]??{score:false,status:'not_scored'});const r=value(right==='vnext'?p.vnext[axis]:p.humanB?.[axis]??{score:false,status:'not_scored'});if(l===null||r===null)continue;n++;if(l===r){agree++;if(l==='UNRESOLVED')unresolvedAgree++}matrix[l]??={};matrix[l][r]=(matrix[l][r]??0)+1}return{axis,comparable:n,agree,diverge:n-agree,agreementRate:n?Number((agree/n).toFixed(6)):null,unresolvedAgree,matrix}}
function kappa(ps:Pair[],axis:Axis,left:'human'|'humanB',right:'vnext'|'humanB'){const vals=ps.map(p=>[value(left==='human'?p.human[axis]:p.humanB?.[axis]??{score:false,status:'not_scored'}),value(right==='vnext'?p.vnext[axis]:p.humanB?.[axis]??{score:false,status:'not_scored'})] as const).filter(x=>x[0]!==null&&x[1]!==null) as [string,string][];if(vals.length<2)return null;const cats=[...new Set(vals.flat())];if(cats.length<2)return null;const n=vals.length,po=vals.filter(([a,b])=>a===b).length/n;const ca=new Map(cats.map(c=>[c,vals.filter(([a])=>a===c).length/n]));const cb=new Map(cats.map(c=>[c,vals.filter(([,b])=>b===c).length/n]));const pe=cats.reduce((s,c)=>s+(ca.get(c)??0)*(cb.get(c)??0),0);return pe===1?null:Number(((po-pe)/(1-pe)).toFixed(6))}
function main(){const all=load(inputDir());const scientific=all.filter(p=>p.scientificUse);const tooling=all.filter(p=>!p.scientificUse);const cohort=(ps:Pair[])=>({axis:AXES.map(a=>({...stats(ps,a,'human','vnext'),kappa:kappa(ps,a,'human','vnext')})),critical:{oCFalsePositive:ps.filter(p=>value(p.vnext.objective)==='O-C'&&value(p.human.objective)!=='O-C'&&value(p.human.objective)!==null).length,oECount:ps.filter(p=>value(p.vnext.objective)==='O-E').length}});console.log(JSON.stringify({schemaVersion:'NATURALISTIC_DESCRIPTIVE_REPORT_V2',methodologicalGate:'ENGINE_NATURALISTIC_VALIDATION_NOT_READY',scientificValidation:'NOT_RUN',humanValidation:scientific.length?'DATA_PRESENT_NOT_INTERPRETED':'NOT_STARTED',productAuthorization:'NOT_AUTHORIZED',pairCounts:{total:all.length,scientific:scientific.length,tooling:tooling.length},scientificCohort:cohort(scientific),toolingCohort:cohort(tooling),note:'Descriptive only. UNRESOLVED is a scored category; NOT_SCORED is excluded from denominators.'},null,2));console.log('ENGINE_NATURALISTIC_VALIDATION_NOT_READY')}
try{main()}catch(e){console.error(e instanceof Error?e.message:String(e));console.log('ENGINE_NATURALISTIC_VALIDATION_NOT_READY');process.exit(1)}
